version: '3.8'

services:
  database:
    image: postgres:16.4
    restart: always
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - ./backend/test:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      - internal
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DATABASE_USERNAME} -d ${DATABASE_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - "8080:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      database:
        condition: service_healthy
    networks:
      - internal

  backend:
    image: ghcr.io/${OWNER}/film-react-nest_backend:latest
    build:
      context: ./backend
    restart: always
    depends_on:
      database:
        condition: service_healthy
    environment:
      PORT: ${PORT}
      DATABASE_HOST: database
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_NAME: ${DATABASE_NAME}
      TYPEORM_SYNCHRONIZE: ${TYPEORM_SYNCHRONIZE}
    ports:
      - "3000:3000"
    networks:
      - internal

  frontend:
    image: ghcr.io/${OWNER}/film-react-nest_frontend:latest
    build:
      context: ./frontend
    volumes:
      - frontend_build:/app/dist
    networks:
      - internal

  server:
    image: ghcr.io/${OWNER}/film-react-nest_server:latest
    build:
      context: ./nginx
    ports:
      - "80:80"
    volumes:
      - frontend_build:/var/www
      - ./backend/public/content:/var/www/content
    depends_on:
      - frontend
      - backend
    networks:
      - internal

volumes:
  db_data:
  pgadmin-data:
  frontend_build:

networks:
  internal:
    driver: bridge
